### ISSUE TITLE
HuskSync & HuskHomes plugins error at load

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#21]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version   1.20.1-adec9ce
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** 
 - HuskSync: https://mclo.gs/RBeAwLN
 - HuskHomes: https://mclo.gs/jMPC8ji

**Steps to Reproduce:**
 1. Install HuskSync & Huskhomes.
 2. setup mysql & redis in config.yml

**Description of issue:**

**Comment by TonimatasDEV** [comment]
> ## Running on Java 17.0.9 (Eclipse Adoptium)
> Magma version 1.20.1-adec9ce
> Bukkit version v1_20_R1
> Forge version 47.2.17
> **Logs:**
> 
> * HuskSync: https://mclo.gs/RBeAwLN
> * HuskHomes: https://mclo.gs/jMPC8ji
> 
> **Steps to Reproduce:**
> 
> 1. Install HuskSync & Huskhomes.
> 2. setup mysql & redis in config.yml
> 
> **Description of issue:**

Try it now

**Comment by sj-hub9796** [comment]
> > ## Running on Java 17.0.9 (Eclipse Adoptium)
> > Magma version 1.20.1-adec9ce
> > Bukkit version v1_20_R1
> > Forge version 47.2.17
> > **Logs:**
> > 
> > * HuskSync: https://mclo.gs/RBeAwLN
> > * HuskHomes: https://mclo.gs/jMPC8ji
> > 
> > **Steps to Reproduce:**
> > 
> > 1. Install HuskSync & Huskhomes.
> > 2. setup mysql & redis in config.yml
> > 
> > **Description of issue:**
> 
> Try it now

```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.magmafoundation.magma.installer.MagmaInstaller.run(MagmaInstaller.java:263)
        at org.magmafoundation.magma.MagmaStart.main(MagmaStart.java:96)
Caused by: java.net.MalformedURLException: no !/ in spec
        at java.base/java.net.URL.<init>(URL.java:708)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at org.magmafoundation.magma.installer.MagmaInstaller$Dependencies.downloadLibraries(MagmaInstaller.java:377)
        at org.magmafoundation.magma.installer.MagmaInstaller$Dependencies.<init>(MagmaInstaller.java:353)
        at org.magmafoundation.magma.installer.MagmaInstaller.<init>(MagmaInstaller.java:75)
        ... 7 more
Caused by: java.lang.NullPointerException: no !/ in spec
        at java.base/sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:177)
        at java.base/sun.net.www.protocol.jar.Handler.parseURL(Handler.java:162)
        at java.base/java.net.URL.<init>(URL.java:703)
        ... 12 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at org.magmafoundation.magma.updater.MagmaUpdater.<clinit>(MagmaUpdater.java:46)
        at org.magmafoundation.magma.MagmaStart.main(MagmaStart.java:103)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 2 more
```

error at launch

**Comment by TonimatasDEV** [comment]
@sj-hub9796 Delete libraries and try again

**Comment by sj-hub9796** [comment]
> @sj-hub9796 Delete libraries and try again

same error

**Comment by sj-hub9796** [comment]
now libraries working.
but plugins still not working.
husksync: https://mclo.gs/qGR8k42
huskhomes: https://mclo.gs/mLsqurq
